version: "3.8"

services:
  apex-app:
    build: .
    ports:
      - "19000:19000"  # Metro bundler
      - "19001:19001"  # Web preview
      - "19002:19002"  # Expo DevTools
    volumes:
      - .:/app
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    stdin_open: true
    tty: true
